version: '3.4'

services:
  blog:
    image: blog
    build:
      context: backend/blog
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 2083:2083
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
