version: '3.4'

services:
  frontend:
    build:
      context: frontend/blog
      dockerfile: ./Dockerfile
    image: blog-frontend
    environment:
      NODE_ENV: production
    ports:
      - 2052:2052

  backend:
    build:
      context: backend/blog
      dockerfile: ./Dockerfile
    image: blog-backend 
    environment:
      NODE_ENV: production
    ports:
      - 2082:2082
